Flask-Plotly-Html-JQuery/Terrorism_App/Terrorism_Dashboard/__init__.py
from flask import Flask

def init_app():
    app = Flask(__name__)

    with app.app_context():

        from Terrorism_Dashboard.core.views import core
        from Terrorism_Dashboard.data.views import data
        from Terrorism_Dashboard.eventCharts.views import eventCharts
        from Terrorism_Dashboard.timeSeries.views import timeSeries
        from Terrorism_Dashboard.worldMap.views import worldMap
        app.register_blueprint(core)
        app.register_blueprint(data)
        app.register_blueprint(eventCharts)
        app.register_blueprint(timeSeries)
        app.register_blueprint(worldMap)

        return app

Flask-Plotly-Html-JQuery/Terrorism_App/Terrorism_Dashboard/core/views.py
# Terrorism_Dashboard/core/views.py
from flask import render_template, request, Blueprint

core = Blueprint('core',__name__)

@core.route('/')
def index():
    return render_template('index.html')

Flask-Plotly-Html-JQuery/Terrorism_App/Terrorism_Dashboard/data/views.py
# Terrorism_Dashboard/data/views.py
from flask import render_template, url_for, Blueprint

data = Blueprint('data',__name__)

@data.route('/data')
def show():
    return render_template('data.html')

Flask-Plotly-Html-JQuery/Terrorism_App/Terrorism_Dashboard/eventCharts/views.py
# Terrorism_Dashboard/eventCharts/views.py
from flask import render_template, request, Blueprint
import plotly
import plotly.graph_objs as go

import pandas as pd
import numpy as np
import json

eventCharts = Blueprint('eventCharts',__name__)

@eventCharts.route('/event-charts')
def chart():
    feature = 'Bar'
    graph = create_plot(feature)
    return render_template('chart.html', plot=graph)

def create_plot(feature):
    if feature == 'Bar':
        N = 40
        x = np.linspace(0, 1, N)
        y = np.random.randn(N)
        df = pd.DataFrame({'x': x, 'y': y}) # creating a sample dataframe
        data = [
            go.Bar(
                x=df['x'], # assign x as the dataframe column 'x'
                y=df['y']
            )
        ]
    else:
        N = 1000
        random_x = np.random.randn(N)
        random_y = np.random.randn(N)

        # Create a trace
        data = [go.Scatter(
            x = random_x,
            y = random_y,
            mode = 'markers'
        )]


    graphJSON = json.dumps(data, cls=plotly.utils.PlotlyJSONEncoder)

    return graphJSON

@eventCharts.route('/charts', methods=['GET', 'POST'])
def change_features():

    feature = request.args['selected']
    graphJSON= create_plot(feature)
    return graphJSON

Flask-Plotly-Html-JQuery/Terrorism_App/Terrorism_Dashboard/timeSeries/views.py
# Terrorism_Dashboard/timeSeries/views.py
from flask import render_template, request, Blueprint
import plotly
import plotly.graph_objs as go

import pandas as pd
import numpy as np
import json

timeSeries = Blueprint('timeSeries',__name__)

df = pd.read_csv("./Terrorism_Dashboard/static/data/Terrorism_data.csv",encoding='latin1')
df['Date'] = pd.to_datetime(df['Date'])
dfx = df.copy(deep=False)

@timeSeries.route('/time-series')
def chart():
    time_span, country = 'Year', 'All'
    graph = create_plot(time_span, country)
    dx = dfx[['country_txt']].sort_values('country_txt')
    country_list = list(dx['country_txt'].unique())
    return render_template('time.html', plot=graph,country_list = country_list)


def create_plot(time_span, country):
    if country == 'All':
        if time_span == "Decade":
            dx = dfx.groupby((dfx['Date'].dt.year//10)*10).agg('count').rename(columns={"country_txt": "Count Of Events"})[['Count Of Events']]
        elif time_span == "Year":
            dx = dfx.groupby(dfx['Date'].dt.year).agg('count').rename(columns={"country_txt": "Count Of Events"})[['Count Of Events']]
        elif time_span == "Month":
            dx = dfx.groupby(dfx['Date'].dt.month).agg('count').rename(columns={"country_txt": "Count Of Events"})[['Count Of Events']]
        elif time_span == "Day":
            dx = dfx.groupby(dfx['Date'].dt.day).agg('count').rename(columns={"country_txt": "Count Of Events"})[['Count Of Events']]
        elif time_span == "WeekDay":
            weekdayDict = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
            dx = dfx.groupby(dfx['Date'].dt.weekday).agg('count').rename(columns={"country_txt": "Count Of Events"})[['Count Of Events']]
            dx.index = weekdayDict
    else:
        if time_span == "Decade":
            dx = dfx[dfx['country_txt']==country].groupby((dfx['Date'].dt.year//10)*10).agg('count').rename(columns={"country_txt": "Count Of Events"})[['Count Of Events']]
        elif time_span == "Year":
            dx = dfx[dfx['country_txt']==country].groupby(dfx['Date'].dt.year).agg('count').rename(columns={"country_txt": "Count Of Events"})[['Count Of Events']]
        elif time_span == "Month":
            dx = dfx[dfx['country_txt']==country].groupby(dfx['Date'].dt.month).agg('count').rename(columns={"country_txt": "Count Of Events"})[['Count Of Events']]
        elif time_span == "Day":
            dx = dfx[dfx['country_txt']==country].groupby(dfx['Date'].dt.day).agg('count').rename(columns={"country_txt": "Count Of Events"})[['Count Of Events']]
        elif time_span == "WeekDay":
            weekdayDict = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
            dx = dfx[dfx['country_txt']==country].groupby(dfx['Date'].dt.weekday).agg('count').rename(columns={"country_txt": "Count Of Events"})[['Count Of Events']]
            dx.index = weekdayDict

    trace = go.Scatter(
    x = dx.index,
    y = dx['Count Of Events'],
    mode = 'lines+markers',
    name = 'Yearly',
    marker = {
            'size': 8,
            'color': 'rgb(51,204,153)',
            'line': {'width': 2}
            }
    )
    graphs = {
        'data' : [trace],
        'layout' : go.Layout(
        title = 'Terrorism Events',
        xaxis = {'title': time_span+"s"},
        yaxis = {'title': '# of Events'},
        hovermode='closest')
    }

    graphJSON = json.dumps(graphs, cls=plotly.utils.PlotlyJSONEncoder)

    return graphJSON

@timeSeries.route('/series', methods=['GET', 'POST'])
def change_features():

    time_span = request.args['time_selected']
    country = request.args['country_selected']
    print(country)
    graphJSON = create_plot(time_span, country)
    return graphJSON

Flask-Plotly-Html-JQuery/Terrorism_App/Terrorism_Dashboard/worldMap/views.py
# Terrorism_Dashboard/worldMap/views.py
from flask import render_template, request, Blueprint
import plotly
import plotly.graph_objs as go

import pandas as pd
import numpy as np
import json

worldMap = Blueprint('worldMap',__name__)

@worldMap.route('/world-map')
def chart():
    return render_template('worldmap.html')

Flask-Plotly-Html-JQuery/Terrorism_App/Terrorism_Dashboard/templates/chart.html
{% extends "index.html"%}
{% block content %}
<h2>Event Charts</h2>
<div class="container">
    <div class="row justify-content-end">
        <div class="col-3">
          <label> Choose Plot Type </label>
          <select class="form-control" id ='plot_type'>
            <option value="Bar">Bar</option>
            <option value="Scatter">Scatter</option>
          </select>
        </div>
    </div>
    <br>
    <br>
    <div class="row justify-content-centre">
        <div class="col-6">
            <div class="chart" id="firstgraph">
                <script>
                    var graphs = {{plot | safe}};
                    Plotly.plot('firstgraph',graphs,{});
                </script>
            </div>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='js/jquery-1.11.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/plots.js') }}"></script>
{% endblock %}

Flask-Plotly-Html-JQuery/Terrorism_App/Terrorism_Dashboard/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <!-- <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1"> -->
    <title>Dashboard</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="../static/css/dashboard.css" rel="stylesheet">
    <!-- For Plotly Integration with HTML -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>

    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

  </head>
  <body>
  <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href={{ url_for('core.index')}}>Dashboard</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Sign In</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">

      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('data.show')}}">
              <!-- <span data-feather="bar-chart-2"></span> -->
              Data
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('timeSeries.chart')}}">
              <!-- <span data-feather="home"></span> -->
              Time Series
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('worldMap.chart')}}">
              <!-- <span data-feather="file"></span> -->
              World Map
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <!-- <span data-feather="shopping-cart"></span> -->
              Event List
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('eventCharts.chart')}}">
              <!-- <span data-feather="users"></span> -->
              Event Charts
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <!-- <span data-feather="bar-chart-2"></span> -->
              Reports
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <div class=" justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Global Terrorism Dashboard</h1>
      </div>
      {% block content %}
      <div>
        <img src="../static/img/Terrorism.jpg" width="1000" height="500">
      </div>
      {% endblock %}
    </main>
  </div>
</div>
      </body>
</html>

Flask-Plotly-Html-JQuery/Terrorism_App/Terrorism_Dashboard/templates/time.html
{% extends "index.html"%}
{% block content %}
<h2>Time Series</h2>
<div class="container">
    <div class="row justify-content-end">
        <div class="col-3">
          <label> Choose Time Period </label>
          <select class="form-control" id ='time_frame'>
            <option value="Year">Year</option>
            <option value="Decade">Decade</option>
            <option value="Month">Month</option>
            <option value="Day">Day</option>
            <option value="WeekDay">WeekDay</option>
          </select>
        </div>
        <div class="col-3">
          <label> Choose Country </label>
          <select class="form-control" id ='country_frame'>
            <option value="All">All</option>
            {% for country in country_list %}
            <option value="{{country}}"">{{country}}</option>
            {% endfor %}
          </select>
        </div>
    </div>
    <br>
    <div class="row justify-content-centre">
        <div class="col-12">
            <div class="chart" id="time-graph">
                <script>
                    var graphs = {{plot | safe}};
                    Plotly.plot('time-graph',graphs,{});
                </script>
            </div>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='js/jquery-1.11.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/plots.js') }}"></script>
{% endblock %}

Flask-Plotly-Html-JQuery/Terrorism_App/Terrorism_Dashboard/templates/worldmap.html
{% extends "index.html"%}
{% block content %}
<h2>Event Charts</h2>
<div class="container">

    <div class="row justify-content-centre">
        <select class="selectpicker" multiple data-live-search="true">
        <option>Mustard</option>
        <option>Ketchup</option>
        <option>Relish</option>
        <option>Mus</option>
        <option>Ket</option>
        <option>Rel</option>
        </select>
    </div>
    <br>
    <div class="row justify-content-centre">
        <div class="col-6">
            <div class="chart" id="firstgraph">
                <script>
                    var graphs = {{plot | safe}};
                    Plotly.plot('firstgraph',graphs,{});
                </script>
            </div>
        </div>
    </div>
  </div>
<script src="{{ url_for('static', filename='js/jquery-1.11.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/plots.js') }}"></script>
{% endblock %}